services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel-collector
    container_name: otel-collector
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      # - "4318:4318"         # OTLP http receiver
      - "55679:55679" # zpages extension
    command:
      [
        "--config=/etc/otelcollector-config.yml",
      ]
    volumes:
      - ./otelcollector/otelcollector-config.yaml:/etc/otelcollector-config.yml
    deploy:
      resources:
        limits:
          memory: 125M
    depends_on:
      - zookeeper
      - kafka
    networks:
      - elk
    restart: always
